# -*- coding: utf-8 -*-
"""coursebzhnews_03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vuiiOB6NfH6HiQd1qUTbDCvPfCYgJWlo

### Проверка того, что наше api работает

Перед началом необходимо собрать docker-образ и запустить контейнер

1. Следовать инструкциям https://github.com/fimochka-sudo/GB_docker_flask_example/blob/main/README.md
2. Далее уже запускать код ниже
"""

import pandas as pd
from sklearn.metrics import roc_auc_score, roc_curve
from urllib import request, parse

X_test = pd.read_csv("X_test.csv")
y_test = pd.read_csv("y_test.csv")

import urllib.request
import json      

def get_prediction(title, text, date):
    body = {'title': title, 
                            'text': text,
                            'date': date} 

    myurl = "http://192.168.0.101:8180/predict"
    req = urllib.request.Request(myurl)
    req.add_header('Content-Type', 'application/json; charset=utf-8')
    jsondata = json.dumps(body)
    jsondataasbytes = jsondata.encode('utf-8')   # needs to be bytes
    req.add_header('Content-Length', len(jsondataasbytes))
    #print (jsondataasbytes)
    response = urllib.request.urlopen(req, jsondataasbytes)
    return json.loads(response.read())['predictions']

get_prediction('War in Ukrane is Fake', 'What will it be? Putin is a tsar.', 'March 1, 2022 ')

# Commented out IPython magic to ensure Python compatibility.
# %%time
predictions = X_test[['title', 'text', 'date']].iloc[:500].apply(lambda x: get_prediction(x[0], x[1], x[2]), 1)

#roc_auc_score(y_score=predictions.values, y_true=y_test.iloc[:500])