# -*- coding: utf-8 -*-
"""CourseBzhNews_02 (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fB-uZpr8Iuay9VxOP7VQ4WbOfW9x-yUk
"""

import pandas as pd
from sklearn.metrics import roc_auc_score,roc_curve
import dill
dill._dill._reverse_typemap['ClassType'] = type

X_test = pd.read_csv("X_test.csv")
y_test = pd.read_csv("y_test.csv")
with open('gradboost_pipeline.dill', 'rb') as in_strm:
    pipeline = dill.load(in_strm)

predictions = pipeline.predict_proba(X_test)
pd.DataFrame({'preds': predictions[:, 1]}).to_csv("test_predictions.csv", index=None)

roc_auc_score(y_score=predictions[:, 1][:], y_true=y_test.iloc[:])